server:
  port: 8888
  
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/kartikmm/config-repo
          username: kartikmm
          password: 238@AlpineWay
          search-paths: userservice, itemservice
        encrypt:
          enabled: false